services:
  postgres:
    image: postgres:15
    container_name: local-users-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1
      POSTGRES_DB: oliver_db
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
